### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by davidheyman** [axismaps/denison#68]
I'm having a really tough time getting this running on a clean server. I think imagick and directory permissions are the major issue. Hopefully we can eliminate some of the problem areas and document the rest.

**Comment by kingfisher13** [comment]
Documented on the [wiki](https://github.com/axismaps/denison/wiki/Installation).

@davidheyman Can I get a fresh install to make sure the order of the steps is correct? I especially want to check the permissions steps from a fresh install as I changed them around a bunch in getting it working.

**Comment by davidheyman** [comment]
Let's talk about this today. I added the build system to the easiest install process might be:

1. Install Linux software
2. Install global node stuff (bower and gulp)
3. Clone from Github in home directory
4. Install bower stuff
5. Install local node stuff for bower
6. Build the files
7. Copy build directory to web server

Building with Gulp gets the permissions right on the CSV files but it can't change directory permissions so you still have to go in there and change the owner of `php/`.

Now all of this is still way too complicated for a regular person so I think we should have a second set of instructions that get you to download a binary (pre-built) from a release and upload via Cyberduck and change the permissions all using FTP. It will have to assume imagemagick is already installed and properly configured.

**Comment by kingfisher13** [comment]
The in-depth instructions are up and work great. The only thing I didn't document was how to install Ubuntu on the server in the first place. 

There is a problem with the "easy" instructions though. Apparently FTP programs can't change ownership/groups (something to do with the underlying security structure that there is no way we can work around). So in order to get the "easy" way to work, you still have to SSH into the server and use the command line. And at that point, there is no difference in difficulty between the "easy" way and the "hard" way.

**Comment by davidheyman** [comment]
What about setting the directory permissions to 777? Does that work but expose the directory to being viewed with the browser?

**Comment by kingfisher13** [comment]
Nope. I've even tried setting the entire test-installation folder to 777 recursively. So everything has all permissions. Still doesn't work.

**Comment by kingfisher13** [comment]
Hmm. A little more research on this reveals:

- On the test-installation folder, setting the permissions to 755/644 actually does seem to work. I think there was a problem with the standard security practices that basically don't allow 777/666 files to even run.
- Setting the permissions to 755/644 creates the `data.json` file and several of the `temp00.pdf` files.  So creation of files is not the problem.
- The error_log that was created is showing problems with (if I read the error correctly) the PostScript install. See this [SO Answer](http://stackoverflow.com/questions/13228370/imagemagick-not-working-with-php).

So, do we know if Ghostscript is installed on this server?
