### ISSUE TITLE
[new content additions] cURL should support more than 5 fields

### ISSUE THREAD

**Issue by kingfisher13** [axismaps/denison#75]

**Comment by kingfisher13** [comment]
8358f6f920242fade78f90ee390ba27acc216b21 attempted to fix this. Problem is, the return data from the server is a plain ole array with numerical keys, i.e. no way to merge this based on the key.

**Comment by davidheyman** [comment]
I'm not sure I understand the problem. Can you post the JSON for what's being returned along with the request you're sending to retrieve it?

**Comment by kingfisher13** [comment]
Sorry, was more writing notes to myself. The function that I was using, `array_merge_recursive`, only works on associative arrays and the server is returning numeric arrays.

So I'm trying to merge these two JSON files:
https://server15963.contentdm.oclc.org/dmwebservices/index.php?q=dmQuery/p15963coll43/0/title!subjec!datea!coveraa!descri/title/1024/1/0/0/0/0/0/0/json
https://server15963.contentdm.oclc.org/dmwebservices/index.php?q=dmQuery/p15963coll43/0/title!latitu!longit/title/1024/1/0/0/0/0/0/0/json
