### ISSUE TITLE
[new content additions] Geocoder choking

### ISSUE THREAD

**Issue by kingfisher13** [axismaps/denison#77]
Mapquest seems to choke on the Herbarium location names. Are we going to move to Getty anyways?

**Comment by davidheyman** [comment]
Not on this round of work. Does this run off lat / lon for everything or just some things?

**Comment by kingfisher13** [comment]
I'm refactoring to grab Lat/Lng if available. For the Herbarium, it is available so that shouldn't be a problem. The text location field is structured in a way that Mapquest doesn't seem to be able to read (e.g. `USA - Ohio - Licking - Newark` ).

**Comment by davidheyman** [comment]
Great. Make sure we can specify the names of the lat / lon fields as well. There are lots of different potential names for those.
