### ISSUE TITLE
[new content additions] `loadImage.php` should handle jp2 as well

### ISSUE THREAD

**Issue by kingfisher13** [axismaps/denison#79]

**Comment by kingfisher13** [comment]
Currently, the Herbarium has 15Mb jp2 pictures which the current function chokes on. It'll do one just fine, but doing multiple doesn't work.

**Comment by davidheyman** [comment]
What year is the image? I'll try it on the DigitalOcean server and see how it is handled there.

**Comment by kingfisher13** [comment]
@davidheyman Not sure what you mean. Do you mean the year for the picture in the db or the year it was created?

One example image is [here](http://cdm15963.contentdm.oclc.org/utils/ajaxhelper/?CISOROOT=p15963coll43&CISOPTR=10&action=2&DMSCALE=5).
